# Generated by Django 3.1.6 on 2021-02-11 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100)),
                ('photograph', models.ImageField(upload_to='image/')),
                ('email_id', models.CharField(max_length=100)),
                ('phone_no', models.CharField(max_length=100)),
                ('pswd', models.CharField(max_length=100)),
                ('Confirm_pswd', models.CharField(max_length=100)),
                ('city_live', models.CharField(max_length=100)),
                ('state_live', models.CharField(max_length=100)),
                ('zip_code', models.CharField(max_length=100)),
                ('id_card', models.ImageField(upload_to='image/')),
                ('date', models.DateField()),
            ],
        ),
    ]
